services:
  portfolio:
    image: hamza-rihani-portfolio
    build: 
      context: .
      dockerfile: Dockerfile
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
     - ./hamza-rihani-portfolio:/usr/local/app
    ports:
      - "3000:3000"
